version: '3.8'

services:
  bs-react:
    build: ./fe
    image: bs-react
    container_name: bs-react
    ports:
      - "6749:6749"
    volumes:
      - ./fe:/fe
    command: ["npm","run", "start-jenkins"]
    networks:
      - app_network
  bs-flask:
    build: ./be
    image: bs-flask
    container_name: bs-flask
    ports:
      - "6748:6748"
    volumes:
      - ./be:/be
    command: [ "flask", "run", "--host", "0.0.0.0", "--port", "6748" ]
    environment:
      FLASK_APP: /be/app.py
      FLASK_ENV: ${FLASK_ENV}
      SQLALCHEMY_DATABASE_URI: mysql://learnix:TomerKakou.123@213.8.44.35:3309/learnix
      SQLALCHEMY_DATABASE_URI_TESTING: mysql://learnix:TomerKakou.123@213.8.44.35:3309/learnix-test
      BASE_URL: http://localhost:6748/api
      FRONT_URL: http://localhost:6749
      SECRET_KEY: ASASLKGHASLKDHGASKLHGASKLDGALSAD
      SENDGRID_API_KEY: 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
      SENDGRID_API_EMAIL: tomerka3@ac.sce.ac.il
    depends_on:
      - bs-react
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
  

