version: '3.8'

services:
  bs-react:
    build: ./fe
    image: bs-react
    container_name: bs-react
    ports:
      - "6749:6749"
    networks:
      - app_network
  bs-flask:
    build: ./be
    image: bs-flask
    container_name: bs-flask
    ports:
      - "6748:6748"
    environment:
      FLASK_APP: /be/app.py
      FLASK_ENV: ${FLASK_ENV}
    depends_on:
      - bs-react
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
  

